export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  CHAT: "/chat",
  LOUNGE: "/lounge",
  NOTIFICATION: "/notification",
  PROFILE: "/profile",
  REGION: "/region",
  SEARCH: "/search",
  LOCATION: "/location",
  HOBBYLIST: "/list/hobby",
  DEALLIST: "/list/deal",
  GROUPDEALLIST: "/list/groupdeal",
};
