export const ROUTES = {
  MAIN: "/",
  HOME: "/home",
  LOGIN: "/login",
  SIGNUP: "/signup",
  CHAT: "/chat",
  LOUNGE: "/lounge",
  NOTIFICATION: "/notification",
  PROFILE: "/profile",
  REGION: "/region",
  SEARCH: "/search",
  LOCATION: "/location",
  POST: "/post",
  HOBBY: "/hobby",
  GROUP_DEAL: "/groupdeal",
  DEAL: "/deal",
  EDITPROFILE: "/profile/edit",
};

export const QUERY_KEYS = {
  MY_ALARM: "myAlarm",
  MY_PROFILE: "myProfile",
  HOBBY_ROOM: "hobbyRoom",
  HOBBY_LIST: "hobbyList",
  HOBBY_READY_LIST: "hobbyReadyList",
  HOBBY_PARTICIPATION_LIST: "hobbyParticipationList",
  HOBBY_MANAGE_LIST: "hobbyManageList",
  HOBBY_FAVORITE_LIST: "hobbyFavoriteList",
  DEAL_LIST: "dealList",
  DEAL_SOLDOUT_LIST:"dealSoldOutList",
  DEAL_PURCHASE_LIST:"dealPurchaseList",
  DEAL_ONSALE_LIST:"dealOnSaleList",
  DEAL_FAVORITE_LIST:"dealFavoriteList",
  CHAT_ROOM_HISTORY: "chatRoomHistory",
  CHAT_LIST: "chatList",
};
